name: nord
version: 0.1.0-dev.2

description: Flutter Nord theme

homepage: https://github.com/chunghha/nord.dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  supercharged: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  effective_dart: ^1.3.0
  
flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: packages/nord/fonts/Nunito-Light.ttf
          weight: 300
        - asset: packages/nord/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/nord/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: packages/nord/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/nord/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: packages/nord/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/nord/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: packages/nord/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Noto Sans CJK
      fonts:
        - asset: packages/nord/fonts/NotoSansCJK-Regular.ttc
          weight: 300
        - asset: packages/nord/fonts/NotoSansCJK-Bold.ttc
          weight: 700
    - family: Tibetan Machine Uni
      fonts:
        - asset: packages/nord/fonts/TibetanMachineUni.ttf
          weight: 300
    - family: Liberation Serif
      fonts:
        - asset: packages/nord/fonts/LiberationSerif-Regular.ttf
          weight: 300
        - asset: packages/nord/fonts/LiberationSerif-Italic.ttf
          weight: 300
          style: italic
        - asset: packages/nord/fonts/LiberationSerif-Bold.ttf
          weight: 700
        - asset: packages/nord/fonts/LiberationSerif-BoldItalic.ttf
          weight: 700
          style: italic